[package]
name = "tutor-nodb"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "basic-server"
path = "src/basic-server.rs" # Specify the path to your binary source file

[dependencies]
actix-rt = "2.10.0"
actix-web = "4.9.0"
